[package]
name = "CorePackages"
author = "Roblox"
license = ""
version = "0.1.0"

[dependencies]
Roact = { git = "https://github.rbx.com/pdoyle/roact-1x-migration" }
Rodux = { git = "https://github.com/Roblox/rodux", rev = "master" }
RoactRodux = { git = "https://github.rbx.com/pdoyle/roact-rodux-1x-migration" }
Cryo = { git = "https://github.com/Roblox/cryo", rev = "roblox" }
LuaDiscussionsDeps = { git = "https://github.rbx.com/Roblox/lua-discussions-deps" }
UIBlox = { git = "https://github.rbx.com/Roblox/uiblox", rev = "master" }
Otter = { git = "https://github.com/Roblox/Otter", rev = "roblox" }
OtterApp = { git = "https://github.com/Roblox/Otter", rev = "master" }
t = { git = "https://github.com/Roblox/t", rev = "master" }

# TODO: CLILUACORE-480
# There are some changes coming soon for Purchase Prompt that we don't want to
# interrupt, we can migrate it to rotriever once those are done
# PurchasePrompt = { git = "https://github.com/Roblox/PurchasePromptScript-Roact", rev = "master"}
