[package]
name = "CorePackages"
author = "Roblox"
license = ""
version = "0.1.0"

[dependencies]
Roact = { git = "https://github.com/roblox/roact", rev = "master" }
Rodux = { git = "https://github.com/Roblox/rodux", rev = "master" }
RoactRodux = { git = "https://github.com/roblox/roact-rodux", rev = "transitioning-roblox-roact-1x" }
Cryo = { git = "https://github.com/Roblox/cryo", rev = "roblox" }
LuaChatDeps = { git = "https://github.rbx.com/Roblox/lua-chat-deps" }
LuaDiscussionsDeps = { git = "https://github.rbx.com/Roblox/lua-discussions-deps" }
UIBlox = { git = "https://github.rbx.com/Roblox/uiblox", rev = "master" }
Otter = { git = "https://github.com/Roblox/Otter", rev = "roblox" }
OtterApp = { git = "https://github.com/Roblox/Otter", rev = "master" }
t = { git = "https://github.com/Roblox/t", rev = "master" }

# The following packages were ported from AppTempCommon
Promise = { git = "https://github.rbx.com/Roblox/lua-promise" }
Result = { git = "https://github.rbx.com/Roblox/lua-result" }
tutils = { git = "https://github.rbx.com/Roblox/tutils" }

PurchasePrompt = { git = "https://github.com/Roblox/PurchasePromptScript-Roact", rev = "master"}
