--[[
	Package link auto-generated by Rotriever
]]
local PackageIndex = script.Parent.Parent

local package = PackageIndex["roblox_rodux-presence-7b4f3bda-87b5d3c2"]["rodux-presence"]

if package.ClassName == "ModuleScript" then
	return require(package)
end

return package